### ISSUE TITLE
0.10.2 RC 问题集中

### ISSUE THREAD

**Issue by GEEKiDoS** [Kirakira-Games/BanGround-Unity#161]
- [x] #165
- [x] #163
- [x] 开屏logo多了unity @Frenqy 
- [x] ELDisplayDetail Index was outside the bounds of the array. (注: 未触发 [assert](https://github.com/Kirakira-Games/BanGround-Unity/blob/master/Assets/Codes/Result/ELDisplayDetail.cs#L32))
- [x] #166
- [x] #164
- [x] #162
...

**Comment by AECBanana** [comment]
呜呜
